// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://ldwvgxpyeicdelcfygqd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkd3ZneHB5ZWljZGVsY2Z5Z3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NjEyMTksImV4cCI6MjA4ODIzNzIxOX0.KfsMyaXqKwewsccdPDLZ5me0JIs0fP7QBVK7cL0YqQU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});